---
name: tkgbuilder
description: Build TkG Arch Linux package
inputs:
  PKGBUILD:
    description: PKGBUILD subdir
    required: false
  OUTDIR:
    description: Output directory to store the built package (relative to $HOME)
    required: false
    default: $HOME/arch-packages
outputs:
  pkgfile0:
    description: "Filename of the first generated package archive. Usually only one."
  pkgfile1:
    description: "Filename of the 2nd generated package archive, etc."
branding:
  color: blue
  icon: archive
runs:
  using: node12
  main: index.js
